export const projects = [
  {id:'margem', title:'Calculadora de margem', tag:'Primeiro projeto', module:'m04', hours:8, level:'Fundamentos', description:'Uma ferramenta de terminal que mostra lucro, margem e preço mínimo de uma venda.', problem:'Um vendedor precisa considerar custo, comissão e despesas para saber se uma venda compensa. As porcentagens devem ter uma base definida e os valores devem usar Decimal.', requirements:['Receber custo, preço e taxas com validação','Calcular lucro líquido e margem sobre a venda','Tratar taxa total maior ou igual a 100%','Usar Decimal e documentar arredondamento','Testar venda lucrativa, prejuízo e entradas inválidas','Escrever README com um exemplo completo'], deliverable:'Código Python, testes automatizados e README com uma simulação. Use números fictícios: a regra é didática e não substitui apuração tributária.', starter:'from decimal import Decimal\n\ndef calcular_lucro(preco: Decimal, custo: Decimal, taxa: Decimal) -> Decimal:\n    """Retorna preço - custo - taxas sobre a venda."""\n    raise NotImplementedError("Implemente e teste a regra")\n\nif __name__ == "__main__":\n    # Receba e valide as entradas aqui\n    pass\n', rubric:'Explique por que margem sobre o preço e acréscimo sobre o custo são medidas diferentes. Uma pessoa deve conseguir executar o exemplo seguindo o README.'},
  {id:'estoque', title:'Controle de estoque no terminal', tag:'Modelagem', module:'m07', hours:12, level:'Construção', description:'Cadastre produtos e registre entradas e saídas com histórico e persistência.', problem:'Uma pequena fábrica precisa consultar o saldo de um SKU e saber por que ele mudou. Não basta guardar um número: uma movimentação precisa de data, tipo e quantidade.', requirements:['Cadastrar SKU único, nome e saldo inicial','Registrar entradas e saídas sem saldo negativo','Salvar e recarregar dados em JSON ou SQLite','Separar interface de terminal e regras de negócio','Testar duplicidade de SKU e saída inválida','Documentar comandos e formato do histórico'], deliverable:'Aplicação CLI, histórico de movimentações, testes e arquivo de exemplo sem dados reais.', starter:'from dataclasses import dataclass\n\n@dataclass\nclass Produto:\n    sku: str\n    nome: str\n    saldo: int = 0\n\nclass Estoque:\n    def __init__(self):\n        self.produtos = {}\n    def cadastrar(self, produto: Produto):\n        raise NotImplementedError\n    def movimentar(self, sku: str, quantidade: int):\n        raise NotImplementedError\n', rubric:'Demonstre que uma operação rejeitada preserva o saldo anterior. Explique como recupera os dados depois de fechar o programa.'},
  {id:'vendas', title:'Analisador de vendas por SKU', tag:'Problema real', module:'m08', hours:14, level:'Construção', description:'Transforme um CSV de pedidos em um relatório útil para planejar produção.', problem:'O mesmo produto aparece em várias linhas e variações. A produção precisa saber a quantidade vendida por SKU no período, sem misturar pedidos cancelados ou duplicados.', requirements:['Ler CSV com cabeçalhos validados e UTF-8','Filtrar um intervalo inclusivo de datas','Excluir cancelamentos e controlar IDs duplicados','Agrupar por SKU e variação sem perder identidade','Exportar ranking e lista de linhas rejeitadas','Testar limites de datas, duplicatas e CSV inválido'], deliverable:'CLI com argumentos, dados fictícios de exemplo, relatório CSV, testes e README. Documente o mapeamento de cabeçalhos; não prometa compatibilidade com todo marketplace.', starter:'import csv\nfrom pathlib import Path\n\ndef ler_vendas(caminho: Path):\n    with caminho.open(encoding="utf-8", newline="") as arquivo:\n        return list(csv.DictReader(arquivo, delimiter=";"))\n\ndef gerar_relatorio(vendas, inicio, fim):\n    raise NotImplementedError("Filtre, valide, agrupe e ordene")\n', rubric:'Mostre uma entrada com duplicata, cancelamento e venda na data limite. Confira manualmente o resultado esperado e inclua esse caso na suíte.'},
  {id:'api', title:'API de pedidos com FastAPI', tag:'Backend', module:'m10', hours:20, level:'Profissional', description:'Crie uma API documentada com validação, banco de dados e testes HTTP.', problem:'Um sistema precisa criar e consultar pedidos sem depender de uma tela específica. A API deve validar o contrato, persistir dados e retornar erros previsíveis.', requirements:['Criar GET /health, POST /pedidos e GET /pedidos/{id}','Validar corpos com Pydantic e retornar 201/404 corretamente','Persistir em SQLite com parâmetros e transações','Separar rotas, modelos e funções de domínio','Testar respostas HTTP com TestClient','Documentar instalação, /docs, configuração e limitações'], deliverable:'Projeto executável no computador, testes HTTP e documentação. Hospede o backend em um serviço que execute Python quando decidir publicar. Pages pode continuar hospedando o frontend.', starter:'from fastapi import FastAPI\nfrom pydantic import BaseModel, Field\n\napp = FastAPI(title="API de pedidos")\n\nclass NovoPedido(BaseModel):\n    sku: str = Field(min_length=1)\n    quantidade: int = Field(gt=0)\n\n@app.get("/health")\ndef health():\n    return {"status":"ok"}\n\n@app.post("/pedidos", status_code=201)\ndef criar(dados: NovoPedido):\n    # Substitua por uma operação persistente e testada\n    raise NotImplementedError\n', rubric:'Explique o que acontece quando o processo reinicia e como os testes isolam o banco. Não use uma lista global como persistência de produção.'},
  {id:'automacao', title:'Pipeline de relatórios', tag:'Automação', module:'m11', hours:14, level:'Profissional', description:'Processe arquivos com logs, validação e proteção contra reimportação.', problem:'Relatórios chegam periodicamente e podem ser enviados duas vezes. A automação precisa ser reproduzível e mostrar o que aceitou, rejeitou e exportou.', requirements:['Separar extração, validação, transformação e exportação','Aceitar uma pasta de entrada por argumento','Evitar contar um pedido duas vezes','Gerar resumo de aceitas e rejeitadas','Registrar etapas sem gravar segredos','Testar duas execuções do mesmo lote'], deliverable:'Pipeline CLI, logs de exemplo, testes, configuração de exemplo e instruções. A execução agendada é uma etapa local opcional; nada será agendado automaticamente pela plataforma.', starter:'import logging\n\nlogger = logging.getLogger(__name__)\n\ndef processar(linhas):\n    """Retorna resultados e erros sem misturar I/O com regras."""\n    raise NotImplementedError\n\ndef main():\n    logging.basicConfig(level=logging.INFO)\n    logger.info("Iniciando processamento")\n    # Conecte as etapas depois de testar cada uma\n\nif __name__ == "__main__":\n    main()\n', rubric:'Mostre que repetir o lote não duplica os números. Demonstre a mensagem emitida quando falta uma coluna obrigatória.'},
  {id:'final', title:'Seu produto Python', tag:'Projeto final', module:'m12', hours:20, level:'Primeira vaga', description:'Escolha um problema conhecido e entregue uma solução que outra pessoa consiga usar.', problem:'Escolha um problema pequeno de estoque, vendas, finanças ou produtividade. Defina a pessoa que vai usar, a entrada, a saída e três comportamentos essenciais. Mantenha o escopo executável.', requirements:['Definir problema, usuário e critérios de aceitação','Organizar o código e usar Git com commits explicativos','Persistir dados e tratar falhas de forma previsível','Testar os comportamentos essenciais e fronteiras','Entregar README reproduzível e demonstração','Escrever decisões técnicas e próximos passos'], deliverable:'Repositório público, código, testes, documentação e uma demonstração curta. Escreva um resumo do problema e das decisões para usar em entrevistas.', starter:'"""Projeto final FutureDev.\n\nProblema:\nPessoa que vai usar:\nEntrada e saída:\nTrês critérios de aceitação:\n"""\n\ndef main():\n    raise NotImplementedError("Comece por uma regra pequena com testes")\n\nif __name__ == "__main__":\n    main()\n', rubric:'Você deve conseguir explicar uma decisão, um bug que corrigiu e um limite da solução. A conclusão aqui é uma autoavaliação; o link não realiza revisão automática do repositório.'}
];

export const careerChecks = [
  {id:'github',text:'GitHub com perfil atualizado e projetos fixados'},
  {id:'cv',text:'Currículo de uma página com links e resultados dos projetos'},
  {id:'linkedin',text:'LinkedIn com título e resumo alinhados a Python'},
  {id:'readme',text:'Projetos com instalação, exemplos e testes documentados'},
  {id:'demo',text:'Demonstração de pelo menos dois projetos funcionando'},
  {id:'explain',text:'Consigo explicar uma decisão técnica e uma falha que corrigi'},
  {id:'git',text:'Consigo trabalhar em branch e revisar um pull request'},
  {id:'interview',text:'Pratiquei explicar um desafio técnico em voz alta'}
];

export const interviewQuestions = [
  {id:'return',prompt:'Qual a diferença entre print e return? Dê um exemplo.',criteria:'Explique que print escreve na saída e return entrega um valor ao chamador. Mostre como uma função de cálculo pode ser reutilizada por uma tela e por um teste.',sample:'Eu usaria return em calcular_lucro para que o resultado pudesse ser usado em um relatório. A interface chamaria a função e usaria print para exibir. Se a função apenas imprimir, o chamador recebe None.'},
  {id:'bug',prompt:'Conte sobre um bug que você encontrou e como o resolveu.',criteria:'Descreva o sintoma, como reproduziu, a hipótese, a mudança e um teste que evita a regressão. Use um caso que você realmente viveu.',sample:'Em meu relatório, vendas do último dia não entravam. Reproduzi com três pedidos nas fronteiras. A comparação usava < em vez de <=. Corrigi a regra e acrescentei testes para o primeiro e o último dia.'},
  {id:'sql',prompt:'Como evitar injeção de SQL? E por que uma transação importa?',criteria:'Explique parâmetros separados do SQL, validação e confirmação ou reversão das operações relacionadas. Não diga apenas "uso ORM".',sample:'Envio os valores como parâmetros, sem concatená-los no SQL. Ao transferir estoque, agrupo retirada e entrada numa transação para que uma falha não deixe só metade da operação registrada.'},
  {id:'api',prompt:'Como você testaria uma API de pedidos?',criteria:'Inclua criação válida, corpo inválido, recurso ausente, persistência e isolamento do banco. Cite status e corpo da resposta.',sample:'Testaria POST válido esperando 201 e os campos do pedido, GET desse id, GET inexistente com 404 e quantidades inválidas. Cada teste usaria um banco isolado para não depender da ordem nem dos dados de produção.'},
  {id:'tradeoff',prompt:'Descreva uma escolha técnica do seu projeto e uma alternativa.',criteria:'Conecte a escolha ao tamanho e às necessidades do problema. Explique um benefício, um custo e quando mudaria de opção.',sample:'Usei SQLite por ser um projeto pequeno e fácil de executar localmente. Ele simplifica a instalação, mas eu reavaliaria para um serviço com muita concorrência de escrita ou várias instâncias de aplicação.'},
  {id:'async',prompt:'Quando async ajuda e quando não resolve o problema?',criteria:'Diferencie espera por I/O de processamento pesado e explique que uma chamada bloqueante dentro de async pode bloquear o loop.',sample:'async pode permitir que outras tarefas continuem enquanto uma consulta de rede é aguardada. Para um cálculo pesado, eu mediria o custo e consideraria processos ou outro desenho. Só adicionar async def não acelera esse cálculo.'}
];

export const resources = [
  {title:'Tutorial oficial do Python',url:'https://docs.python.org/pt-br/3/tutorial/',description:'Referência para voltar aos conceitos e ler exemplos oficiais.'},
  {title:'Biblioteca padrão',url:'https://docs.python.org/pt-br/3/library/',description:'Documentação de csv, json, pathlib, unittest e sqlite3.'},
  {title:'Git: livro gratuito',url:'https://git-scm.com/book/pt-br/v2',description:'Versionamento, branches e colaboração.'},
  {title:'Tutorial do FastAPI',url:'https://fastapi.tiangolo.com/pt/tutorial/',description:'Da primeira rota até validação, banco e testes.'},
  {title:'SQL: documentação SQLite',url:'https://www.sqlite.org/lang.html',description:'Sintaxe e comportamento das consultas SQL.'},
  {title:'Empacotamento Python',url:'https://packaging.python.org/pt-br/latest/tutorials/installing-packages/',description:'Instalação de pacotes e ambientes isolados.'}
];
